CREATE TABLE IF NOT EXISTS AUTORIDAD(
   ID  INT NOT NULL,
   NOMBRE VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS AUTORIDAD ADD CONSTRAINT AUTHORITY_NAME UNIQUE (NOMBRE);

CREATE TABLE IF NOT EXISTS USUARIO(
   ID SERIAL,
   CUENTA_EXPIRADA BOOLEAN,
   CUENTA_BLOQUEADA BOOLEAN,
   CREDENCIALES_EXPIRADAS BOOLEAN,
   ACTIVO BOOLEAN,
   CONTRASENA VARCHAR(255),
   NOMBRE_USUARIO VARCHAR(255),
   PRIMARY KEY (ID)
);


ALTER TABLE IF EXISTS USUARIO ADD CONSTRAINT USER_USER_NAME UNIQUE (NOMBRE_USUARIO);

CREATE TABLE IF NOT EXISTS AUTORIDADES_USUARIO(
   ID_USUARIO INT NOT NULL,
   ID_AUTORIDAD INT NOT NULL,
   PRIMARY KEY (ID_USUARIO, ID_AUTORIDAD)
);

ALTER TABLE IF EXISTS AUTORIDADES_USUARIO ADD CONSTRAINT USERS_AUTHORITIES_AUTHORITY
  FOREIGN KEY (ID_AUTORIDAD) REFERENCES AUTORIDAD(ID);

ALTER TABLE IF EXISTS AUTORIDADES_USUARIO ADD CONSTRAINT USERS_AUTHORITIES_USER_
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);
