INSERT INTO AUTORIDAD(ID, NOMBRE) VALUES (-1, 'DEACTIVATED');
INSERT INTO AUTORIDAD(ID, NOMBRE) VALUES (1, 'SUPER');
INSERT INTO AUTORIDAD(ID, NOMBRE) VALUES (2, 'SOCIO');
INSERT INTO AUTORIDAD(ID, NOMBRE) VALUES (3, 'VALIDADOR');
