INSERT INTO USUARIO(ID, NOMBRE_USUARIO, CONTRASENA, CUENTA_EXPIRADA, CUENTA_BLOQUEADA, CREDENCIALES_EXPIRADAS, ACTIVO)
  VALUES (1, 'super@super.com', /*super1234*/'$2a$08$GJpkZ9xXtQ.UfmEZrQDjyuDjM/jkcuDsOVo.halMtF5SCvkMqCHHO', FALSE, FALSE, FALSE, TRUE);


INSERT INTO AUTORIDADES_USUARIO (ID_USUARIO, ID_AUTORIDAD) VALUES (1, 1);

